### ISSUE TITLE
[REQ] Option to hide other panel at start and with key combination.

### ISSUE THREAD

**Issue by jnko** [bugnano/rrr#7]
Please add a commandline option to start rnr with only one panel (something like --hidepanel) and also add a key combination to hide the other panel in runtime, for example CTRL-H to hide/unhide.

I often use rnr with quite long filenames and really like the fuzzy filter, but it would be great to just hide the other panel to see the full filename.

Thanks in advance

**Comment by bugnano** [comment]
Hey, thanks for the idea.
OK, I see how that can be useful, I'll do it, but I don't promise any time.

**Comment by bugnano** [comment]
On second thought:
Given that a single panel mode can have some edge cases (for example: single panel mode and quickview are incompatible), would an option to display the panels one on top of each other instead of side-by-side solve your problem?

Advantage:
You can still see very long file names

Disadvantage:
You will only see half of the files at a time

**Comment by bugnano** [comment]
rnr version 1.0.10 implements vertical panel layout, that can be invoked via command line with the `-v` option, or runtime with the `ALT-V` key combination.
Try it, and if you don't need the single panel layout anymore, tell me and we can close this issue.

**Comment by jnko** [comment]
Thanks very nice. In addition with my just created PR this solution is perfect.

**Comment by jnko** [comment]
Closed.
